changelog:
  categories:
    - title: New features
      labels:
        - feature
    - title: Improvements
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Other changes
      labels:
        - "*"
